export let a = {
    "next": 0,
    "notes": [{
        "delay": 1.2
    }, {
        "delay": 3
    }, {
        "delay": 5
    }, {
        "delay": 6.8
    }, {
        "delay": 8.7
    }, {
        "delay": 10.6
    }, {
        "delay": 12.5
    }, {
        "delay": 16.3
    }, {
        "delay": 18.1
    }, {
        "delay": 19.9
    }, {
        "delay": 21.8
    }, {
        "delay": 23.7
    }, {
        "delay": 25.6
    }, {
        "delay": 27.4
    }, {
        "delay": 29.3
    }, {
        "delay": 31.3
    }, {
        "delay": 33
    }, {
        "delay": 35
    }, {
        "delay": 36.8
    }, {
        "delay": 38.6
    }, {
        "delay": 40.5
    }, {
        "delay": 42.5
    }, {
        "delay": 44.3
    }, {
        "delay": 46.2
    }, {
        "delay": 47.1
    }, {
        "delay": 48
    }, {
        "delay": 49
    }, {
        "delay": 49.9
    }, {
        "delay": 50.8
    }, {
        "delay": 51.8
    }, {
        "delay": 52.7
    }, {
        "delay": 53.8
    }, {
        "delay": 54.6
    }, {
        "delay": 57.5
    }, {
        "delay": 58.3
    }, {
        "delay": 61.1
    }, {
        "delay": 62.1
    }, {
        "delay": 64.9
    }, {
        "delay": 65.9
    }, {
        "delay": 68.8
    }, {
        "delay": 71.5
    }, {
        "delay": 74.3
    }, {
        "delay": 76.2
    }, {
        "delay": 78.1
    }, {
        "delay": 79.9
    }, {
        "delay": 81.8
    }, {
        "delay": 83.7
    }, {
        "delay": 85.1
    }, {
        "delay": 86.4
    }, {
        "delay": 87.8
    }, {
        "delay": 89.2
    }, {
        "delay": 90.7
    }, {
        "delay": 91.6
    }, {
        "delay": 92.6
    }, {
        "delay": 93.5
    }, {
        "delay": 94.4
    }, {
        "delay": 95.4
    }, {
        "delay": 96.3
    }, {
        "delay": 98.7
    }, {
        "delay": 100.6
    }, {
        "delay": 102.5
    }, {
        "delay": 104.4
    }, {
        "delay": 106.3
    }, {
        "delay": 108.1
    }, {
        "delay": 110
    }, {
        "delay": 111.8
    }, {
        "delay": 113.7
    }, {
        "delay": 115.5
    }, {
        "delay": 117.4
    }, {
        "delay": 119.3
    }, {
        "delay": 121.3
    }, {
        "delay": 123.1
    }, {
        "delay": 125
    }, {
        "delay": 126.8
    }, {
        "delay": 128.8
    }, {
        "delay": 130.7
    }, {
        "delay": 132.5
    }, {
        "delay": 134.3
    }, {
        "delay": 136.2
    }, {
        "delay": 138.1
    }, {
        "delay": 139.9
    }, {
        "delay": 141.8
    }, {
        "delay": 143.7
    }]
}
export let s = {
    "next": 0,
    "notes": [{
        "delay": 1.6
    }, {
        "delay": 3.4
    }, {
        "delay": 5.3
    }, {
        "delay": 7.1
    }, {
        "delay": 9.1
    }, {
        "delay": 10.9
    }, {
        "delay": 12.8
    }, {
        "delay": 16.6
    }, {
        "delay": 18.4
    }, {
        "delay": 20.3
    }, {
        "delay": 22.2
    }, {
        "delay": 24.1
    }, {
        "delay": 26
    }, {
        "delay": 27.8
    }, {
        "delay": 29.7
    }, {
        "delay": 31.7
    }, {
        "delay": 33.4
    }, {
        "delay": 35.3
    }, {
        "delay": 37.1
    }, {
        "delay": 39
    }, {
        "delay": 40.9
    }, {
        "delay": 42.8
    }, {
        "delay": 44.7
    }, {
        "delay": 55.6
    }, {
        "delay": 56.5
    }, {
        "delay": 59.3
    }, {
        "delay": 60.1
    }, {
        "delay": 63.1
    }, {
        "delay": 63.9
    }, {
        "delay": 66.8
    }, {
        "delay": 67.8
    }, {
        "delay": 69.2
    }, {
        "delay": 71.1
    }, {
        "delay": 72
    }, {
        "delay": 72.9
    }, {
        "delay": 74.8
    }, {
        "delay": 76.6
    }, {
        "delay": 78.5
    }, {
        "delay": 80.4
    }, {
        "delay": 82.2
    }, {
        "delay": 84.1
    }, {
        "delay": 85.5
    }, {
        "delay": 86.9
    }, {
        "delay": 88.2
    }, {
        "delay": 89.7
    }, {
        "delay": 91.2
    }, {
        "delay": 92.1
    }, {
        "delay": 93
    }, {
        "delay": 94
    }, {
        "delay": 94.9
    }, {
        "delay": 95.8
    }, {
        "delay": 96.8
    }, {
        "delay": 99.1
    }, {
        "delay": 100.9
    }, {
        "delay": 102.9
    }, {
        "delay": 104.7
    }, {
        "delay": 106.6
    }, {
        "delay": 108.5
    }, {
        "delay": 110.4
    }, {
        "delay": 112.5
    }, {
        "delay": 114.1
    }, {
        "delay": 115.9
    }, {
        "delay": 117.8
    }, {
        "delay": 119.7
    }, {
        "delay": 121.6
    }, {
        "delay": 123.4
    }, {
        "delay": 125.3
    }, {
        "delay": 127.2
    }, {
        "delay": 129.2
    }, {
        "delay": 131.5
    }, {
        "delay": 133.3
    }, {
        "delay": 135.2
    }, {
        "delay": 137.1
    }, {
        "delay": 139
    }, {
        "delay": 140.9
    }, {
        "delay": 142.8
    }]
}
export let d = {
    "next": 0,
    "notes": [{
        "delay": 1.9
    }, {
        "delay": 3.8
    }, {
        "delay": 4.5
    }, {
        "delay": 5.7
    }, {
        "delay": 7.5
    }, {
        "delay": 8.2
    }, {
        "delay": 9.4
    }, {
        "delay": 11.3
    }, {
        "delay": 12
    }, {
        "delay": 13.1
    }, {
        "delay": 16.9
    }, {
        "delay": 18.7
    }, {
        "delay": 19.4
    }, {
        "delay": 20.6
    }, {
        "delay": 22.5
    }, {
        "delay": 23.2
    }, {
        "delay": 24.4
    }, {
        "delay": 26.3
    }, {
        "delay": 27
    }, {
        "delay": 28.1
    }, {
        "delay": 30
    }, {
        "delay": 30.4
    }, {
        "delay": 31.9
    }, {
        "delay": 33.8
    }, {
        "delay": 34.5
    }, {
        "delay": 35.6
    }, {
        "delay": 37.5
    }, {
        "delay": 38.2
    }, {
        "delay": 39.4
    }, {
        "delay": 41.3
    }, {
        "delay": 42
    }, {
        "delay": 43.1
    }, {
        "delay": 45
    }, {
        "delay": 45.3
    }, {
        "delay": 54.2
    }, {
        "delay": 55.1
    }, {
        "delay": 57.9
    }, {
        "delay": 58.8
    }, {
        "delay": 61.6
    }, {
        "delay": 62.6
    }, {
        "delay": 65.4
    }, {
        "delay": 66.3
    }, {
        "delay": 69.6
    }, {
        "delay": 70.6
    }, {
        "delay": 72.5
    }, {
        "delay": 73.4
    }, {
        "delay": 75.2
    }, {
        "delay": 77.1
    }, {
        "delay": 79
    }, {
        "delay": 80.8
    }, {
        "delay": 82.7
    }, {
        "delay": 84.6
    }, {
        "delay": 85.9
    }, {
        "delay": 87.3
    }, {
        "delay": 88.7
    }, {
        "delay": 90.2
    }, {
        "delay": 99.4
    }, {
        "delay": 101.3
    }, {
        "delay": 102
    }, {
        "delay": 103.2
    }, {
        "delay": 105
    }, {
        "delay": 105.7
    }, {
        "delay": 106.9
    }, {
        "delay": 108.8
    }, {
        "delay": 109.5
    }, {
        "delay": 110.7
    }, {
        "delay": 112.8
    }, {
        "delay": 114.4
    }, {
        "delay": 116.3
    }, {
        "delay": 116.9
    }, {
        "delay": 118.1
    }, {
        "delay": 120
    }, {
        "delay": 120.7
    }, {
        "delay": 121.9
    }, {
        "delay": 123.8
    }, {
        "delay": 124.4
    }, {
        "delay": 125.7
    }, {
        "delay": 127.5
    }, {
        "delay": 129.6
    }, {
        "delay": 131
    }, {
        "delay": 132.8
    }, {
        "delay": 134.7
    }, {
        "delay": 136.6
    }, {
        "delay": 138.5
    }, {
        "delay": 140.4
    }, {
        "delay": 142.3
    }]
}
export let f = {
    "next": 0,
    "notes": [{
        "delay": 2.1
    }, {
        "delay": 4
    }, {
        "delay": 5.9
    }, {
        "delay": 7.9
    }, {
        "delay": 9.6
    }, {
        "delay": 11.6
    }, {
        "delay": 13.4
    }, {
        "delay": 17.1
    }, {
        "delay": 19
    }, {
        "delay": 20.9
    }, {
        "delay": 22.8
    }, {
        "delay": 24.7
    }, {
        "delay": 26.6
    }, {
        "delay": 28.4
    }, {
        "delay": 32.2
    }, {
        "delay": 34
    }, {
        "delay": 35.9
    }, {
        "delay": 37.9
    }, {
        "delay": 39.7
    }, {
        "delay": 41.6
    }, {
        "delay": 43.4
    }, {
        "delay": 56
    }, {
        "delay": 57
    }, {
        "delay": 59.7
    }, {
        "delay": 60.7
    }, {
        "delay": 63.5
    }, {
        "delay": 64.5
    }, {
        "delay": 67.2
    }, {
        "delay": 68.3
    }, {
        "delay": 70.1
    }, {
        "delay": 73.9
    }, {
        "delay": 75.7
    }, {
        "delay": 77.6
    }, {
        "delay": 79.5
    }, {
        "delay": 81.3
    }, {
        "delay": 83.2
    }, {
        "delay": 99.7
    }, {
        "delay": 101.6
    }, {
        "delay": 103.5
    }, {
        "delay": 105.4
    }, {
        "delay": 107.2
    }, {
        "delay": 109
    }, {
        "delay": 110.9
    }, {
        "delay": 114.6
    }, {
        "delay": 116.5
    }, {
        "delay": 118.4
    }, {
        "delay": 120.4
    }, {
        "delay": 122.2
    }, {
        "delay": 124
    }, {
        "delay": 125.9
    }, {
        "delay": 127.9
    }, {
        "delay": 130.1
    }, {
        "delay": 132
    }, {
        "delay": 133.8
    }, {
        "delay": 135.7
    }, {
        "delay": 137.6
    }, {
        "delay": 139.4
    }, {
        "delay": 141.4
    }, {
        "delay": 143.3
    }]
}
export let song = {
    "name": "KeyBeats",
    "id": "keybeats",
    "src": "assets/audio/music/keybeats.mp3",
    "duration": 146.33795,
    "globalDuration": 4,
    "maxMiss": 10,
    "difficulty": 'easy',
    "colorScheme": 'blue',
    "waveColor": '#f1faff',
    "tracks": [a, s, d, f]
}