export let a = {
    "next": 0,
    "notes": [{
        "delay": 1.2
    }, {
        "delay": 2.5
    }, {
        "delay": 3.1
    }, {
        "delay": 5
    }, {
        "delay": 6.2
    }, {
        "delay": 6.8
    }, {
        "delay": 8.7
    }, {
        "delay": 10
    }, {
        "delay": 10.6
    }, {
        "delay": 12.4
    }, {
        "delay": 13.8
    }, {
        "delay": 14.4
    }, {
        "delay": 15
    }, {
        "delay": 15.7
    }, {
        "delay": 16.3
    }, {
        "delay": 17.5
    }, {
        "delay": 18.1
    }, {
        "delay": 19.9
    }, {
        "delay": 21.3
    }, {
        "delay": 21.8
    }, {
        "delay": 23.7
    }, {
        "delay": 25
    }, {
        "delay": 25.6
    }, {
        "delay": 27.5
    }, {
        "delay": 28.8
    }, {
        "delay": 29.3
    }, {
        "delay": 31.2
    }, {
        "delay": 32.6
    }, {
        "delay": 33.1
    }, {
        "delay": 34.9
    }, {
        "delay": 36.3
    }, {
        "delay": 36.8
    }, {
        "delay": 38.7
    }, {
        "delay": 40
    }, {
        "delay": 40.6
    }, {
        "delay": 42.4
    }, {
        "delay": 43.8
    }, {
        "delay": 44.3
    }, {
        "delay": 46.5
    }, {
        "delay": 47.1
    }, {
        "delay": 48
    }, {
        "delay": 48.9
    }, {
        "delay": 49.8
    }, {
        "delay": 50.7
    }, {
        "delay": 51.6
    }, {
        "delay": 52.6
    }, {
        "delay": 53.6
    }, {
        "delay": 55
    }, {
        "delay": 55.5
    }, {
        "delay": 55.9
    }, {
        "delay": 56.3
    }, {
        "delay": 57.4
    }, {
        "delay": 57.8
    }, {
        "delay": 58.2
    }, {
        "delay": 59.3
    }, {
        "delay": 60
    }, {
        "delay": 61.2
    }, {
        "delay": 61.6
    }, {
        "delay": 61.9
    }, {
        "delay": 63
    }, {
        "delay": 63.4
    }, {
        "delay": 63.7
    }, {
        "delay": 64.9
    }, {
        "delay": 65.2
    }, {
        "delay": 65.6
    }, {
        "delay": 66.8
    }, {
        "delay": 67.2
    }, {
        "delay": 68.7
    }, {
        "delay": 70.6
    }, {
        "delay": 72.3
    }, {
        "delay": 74.3
    }, {
        "delay": 76.2
    }, {
        "delay": 78
    }, {
        "delay": 79.5
    }, {
        "delay": 79.9
    }, {
        "delay": 81.8
    }, {
        "delay": 83.6
    }, {
        "delay": 84.9
    }, {
        "delay": 86.8
    }, {
        "delay": 88.7
    }, {
        "delay": 90.6
    }, {
        "delay": 92.5
    }, {
        "delay": 94.4
    }, {
        "delay": 96.3
    }, {
        "delay": 98.7
    }, {
        "delay": 100.1
    }, {
        "delay": 100.6
    }, {
        "delay": 102.4
    }, {
        "delay": 103.8
    }, {
        "delay": 104.3
    }, {
        "delay": 106.2
    }, {
        "delay": 107.6
    }, {
        "delay": 108.1
    }, {
        "delay": 109.9
    }, {
        "delay": 111.3
    }, {
        "delay": 111.8
    }, {
        "delay": 113.7
    }, {
        "delay": 115.1
    }, {
        "delay": 115.6
    }, {
        "delay": 117.5
    }, {
        "delay": 118.7
    }, {
        "delay": 119.3
    }, {
        "delay": 121.2
    }, {
        "delay": 122.6
    }, {
        "delay": 123.1
    }, {
        "delay": 124.9
    }, {
        "delay": 126.3
    }, {
        "delay": 126.8
    }, {
        "delay": 128.7
    }, {
        "delay": 130.1
    }, {
        "delay": 130.6
    }, {
        "delay": 130.9
    }, {
        "delay": 131.9
    }, {
        "delay": 132.4
    }, {
        "delay": 132.8
    }, {
        "delay": 133.8
    }, {
        "delay": 134.3
    }, {
        "delay": 134.6
    }, {
        "delay": 135.3
    }, {
        "delay": 136.2
    }, {
        "delay": 136.5
    }, {
        "delay": 137.6
    }, {
        "delay": 138.1
    }, {
        "delay": 138.4
    }, {
        "delay": 139.5
    }, {
        "delay": 140
    }, {
        "delay": 140.3
    }, {
        "delay": 140.9
    }, {
        "delay": 141.8
    }, {
        "delay": 142.2
    }, {
        "delay": 143.2
    }]
}
export let s = {
    "next": 0,
    "notes": [{
        "delay": 1.5
    }, {
        "delay": 2.6
    }, {
        "delay": 3.4
    }, {
        "delay": 5.3
    }, {
        "delay": 6.3
    }, {
        "delay": 7.2
    }, {
        "delay": 9
    }, {
        "delay": 10.1
    }, {
        "delay": 10.9
    }, {
        "delay": 12.8
    }, {
        "delay": 13.9
    }, {
        "delay": 14.6
    }, {
        "delay": 14.9
    }, {
        "delay": 15.3
    }, {
        "delay": 15.6
    }, {
        "delay": 15.9
    }, {
        "delay": 16.6
    }, {
        "delay": 17.6
    }, {
        "delay": 18.5
    }, {
        "delay": 20.3
    }, {
        "delay": 21.4
    }, {
        "delay": 22.1
    }, {
        "delay": 24.1
    }, {
        "delay": 25.1
    }, {
        "delay": 26
    }, {
        "delay": 27.8
    }, {
        "delay": 28.9
    }, {
        "delay": 29.7
    }, {
        "delay": 30.1
    }, {
        "delay": 31.6
    }, {
        "delay": 32.7
    }, {
        "delay": 33.5
    }, {
        "delay": 35.3
    }, {
        "delay": 36.4
    }, {
        "delay": 37.1
    }, {
        "delay": 37.5
    }, {
        "delay": 39
    }, {
        "delay": 40.1
    }, {
        "delay": 40.9
    }, {
        "delay": 42.8
    }, {
        "delay": 43.9
    }, {
        "delay": 44.7
    }, {
        "delay": 45
    }, {
        "delay": 54.1
    }, {
        "delay": 55.6
    }, {
        "delay": 56.5
    }, {
        "delay": 57.5
    }, {
        "delay": 58.4
    }, {
        "delay": 59.4
    }, {
        "delay": 59.7
    }, {
        "delay": 60.3
    }, {
        "delay": 61.2
    }, {
        "delay": 62.2
    }, {
        "delay": 63.1
    }, {
        "delay": 64
    }, {
        "delay": 65
    }, {
        "delay": 65.9
    }, {
        "delay": 66.9
    }, {
        "delay": 67.5
    }, {
        "delay": 67.9
    }, {
        "delay": 69
    }, {
        "delay": 70.6
    }, {
        "delay": 72
    }, {
        "delay": 72.4
    }, {
        "delay": 73.8
    }, {
        "delay": 74.3
    }, {
        "delay": 76.5
    }, {
        "delay": 78.1
    }, {
        "delay": 80
    }, {
        "delay": 81.4
    }, {
        "delay": 81.9
    }, {
        "delay": 83.2
    }, {
        "delay": 83.8
    }, {
        "delay": 84.6
    }, {
        "delay": 85.3
    }, {
        "delay": 86.5
    }, {
        "delay": 87.2
    }, {
        "delay": 88.4
    }, {
        "delay": 89.1
    }, {
        "delay": 90.3
    }, {
        "delay": 91
    }, {
        "delay": 92.1
    }, {
        "delay": 92.8
    }, {
        "delay": 94
    }, {
        "delay": 94.7
    }, {
        "delay": 96
    }, {
        "delay": 96.6
    }, {
        "delay": 99
    }, {
        "delay": 100.2
    }, {
        "delay": 100.9
    }, {
        "delay": 102.8
    }, {
        "delay": 103.9
    }, {
        "delay": 104.6
    }, {
        "delay": 105
    }, {
        "delay": 106.6
    }, {
        "delay": 107.6
    }, {
        "delay": 108.4
    }, {
        "delay": 110.3
    }, {
        "delay": 111.4
    }, {
        "delay": 112.2
    }, {
        "delay": 114
    }, {
        "delay": 115.2
    }, {
        "delay": 115.9
    }, {
        "delay": 117.8
    }, {
        "delay": 118.8
    }, {
        "delay": 119.7
    }, {
        "delay": 121.5
    }, {
        "delay": 122.6
    }, {
        "delay": 123.4
    }, {
        "delay": 125.3
    }, {
        "delay": 126.4
    }, {
        "delay": 127.2
    }, {
        "delay": 127.5
    }, {
        "delay": 129.1
    }, {
        "delay": 129.7
    }, {
        "delay": 131
    }, {
        "delay": 131.6
    }, {
        "delay": 132.9
    }, {
        "delay": 133.4
    }, {
        "delay": 134.7
    }, {
        "delay": 135.7
    }, {
        "delay": 136.6
    }, {
        "delay": 137.2
    }, {
        "delay": 138.5
    }, {
        "delay": 139.1
    }, {
        "delay": 140.3
    }, {
        "delay": 141.3
    }, {
        "delay": 142.2
    }, {
        "delay": 142.8
    }, {
        "delay": 143.7
    }]
}
export let d = {
    "next": 0,
    "notes": [{
        "delay": 1.8
    }, {
        "delay": 2.7
    }, {
        "delay": 3.8
    }, {
        "delay": 4.4
    }, {
        "delay": 5.6
    }, {
        "delay": 6.4
    }, {
        "delay": 7.5
    }, {
        "delay": 8.2
    }, {
        "delay": 9.3
    }, {
        "delay": 10.2
    }, {
        "delay": 11.3
    }, {
        "delay": 11.9
    }, {
        "delay": 13.1
    }, {
        "delay": 14
    }, {
        "delay": 14.7
    }, {
        "delay": 15.4
    }, {
        "delay": 16.9
    }, {
        "delay": 17.7
    }, {
        "delay": 18.8
    }, {
        "delay": 19.5
    }, {
        "delay": 20.6
    }, {
        "delay": 21.5
    }, {
        "delay": 22.5
    }, {
        "delay": 23.3
    }, {
        "delay": 24.3
    }, {
        "delay": 25.2
    }, {
        "delay": 26.3
    }, {
        "delay": 27
    }, {
        "delay": 28.2
    }, {
        "delay": 29
    }, {
        "delay": 30.4
    }, {
        "delay": 31.9
    }, {
        "delay": 32.8
    }, {
        "delay": 33.8
    }, {
        "delay": 34.5
    }, {
        "delay": 35.6
    }, {
        "delay": 36.5
    }, {
        "delay": 37.9
    }, {
        "delay": 39.4
    }, {
        "delay": 40.2
    }, {
        "delay": 41.2
    }, {
        "delay": 42
    }, {
        "delay": 43.1
    }, {
        "delay": 44
    }, {
        "delay": 45.4
    }, {
        "delay": 54.6
    }, {
        "delay": 56.9
    }, {
        "delay": 58.8
    }, {
        "delay": 60.7
    }, {
        "delay": 62.6
    }, {
        "delay": 64.4
    }, {
        "delay": 66.3
    }, {
        "delay": 68.3
    }, {
        "delay": 69.4
    }, {
        "delay": 70.1
    }, {
        "delay": 71
    }, {
        "delay": 71.6
    }, {
        "delay": 72.8
    }, {
        "delay": 73.4
    }, {
        "delay": 74.7
    }, {
        "delay": 75.3
    }, {
        "delay": 75.6
    }, {
        "delay": 76
    }, {
        "delay": 76.9
    }, {
        "delay": 77.6
    }, {
        "delay": 78.4
    }, {
        "delay": 79.1
    }, {
        "delay": 80.3
    }, {
        "delay": 80.9
    }, {
        "delay": 82.2
    }, {
        "delay": 82.8
    }, {
        "delay": 84.3
    }, {
        "delay": 85.5
    }, {
        "delay": 86.3
    }, {
        "delay": 87.4
    }, {
        "delay": 88.2
    }, {
        "delay": 89.3
    }, {
        "delay": 90
    }, {
        "delay": 91.2
    }, {
        "delay": 91.9
    }, {
        "delay": 93.1
    }, {
        "delay": 93.8
    }, {
        "delay": 95
    }, {
        "delay": 95.7
    }, {
        "delay": 96.8
    }, {
        "delay": 99.3
    }, {
        "delay": 100.3
    }, {
        "delay": 101.3
    }, {
        "delay": 101.9
    }, {
        "delay": 103.1
    }, {
        "delay": 104
    }, {
        "delay": 105.3
    }, {
        "delay": 105.7
    }, {
        "delay": 106.9
    }, {
        "delay": 107.7
    }, {
        "delay": 108.8
    }, {
        "delay": 109.5
    }, {
        "delay": 110.6
    }, {
        "delay": 111.5
    }, {
        "delay": 112.6
    }, {
        "delay": 112.8
    }, {
        "delay": 114.3
    }, {
        "delay": 115.3
    }, {
        "delay": 116.3
    }, {
        "delay": 117
    }, {
        "delay": 118.1
    }, {
        "delay": 118.9
    }, {
        "delay": 120
    }, {
        "delay": 120.4
    }, {
        "delay": 121.9
    }, {
        "delay": 122.8
    }, {
        "delay": 123.8
    }, {
        "delay": 124.4
    }, {
        "delay": 125.6
    }, {
        "delay": 126.5
    }, {
        "delay": 127.9
    }, {
        "delay": 129.4
    }, {
        "delay": 131.3
    }, {
        "delay": 133.2
    }, {
        "delay": 134.9
    }, {
        "delay": 136.9
    }, {
        "delay": 140.5
    }, {
        "delay": 142.5
    }]
}
export let f = {
    "next": 0,
    "notes": [{
        "delay": 2.1
    }, {
        "delay": 4
    }, {
        "delay": 5.8
    }, {
        "delay": 7.9
    }, {
        "delay": 9.7
    }, {
        "delay": 11.5
    }, {
        "delay": 13.4
    }, {
        "delay": 17.2
    }, {
        "delay": 19
    }, {
        "delay": 20.9
    }, {
        "delay": 22.9
    }, {
        "delay": 24.6
    }, {
        "delay": 26.6
    }, {
        "delay": 28.4
    }, {
        "delay": 32.2
    }, {
        "delay": 34.1
    }, {
        "delay": 35.9
    }, {
        "delay": 38.2
    }, {
        "delay": 39.6
    }, {
        "delay": 41.5
    }, {
        "delay": 43.4
    }, {
        "delay": 45.7
    }, {
        "delay": 69.6
    }, {
        "delay": 71.3
    }, {
        "delay": 73.2
    }, {
        "delay": 75
    }, {
        "delay": 77.2
    }, {
        "delay": 78.8
    }, {
        "delay": 80.7
    }, {
        "delay": 82.5
    }, {
        "delay": 85.9
    }, {
        "delay": 87.8
    }, {
        "delay": 89.7
    }, {
        "delay": 91.6
    }, {
        "delay": 93.4
    }, {
        "delay": 95.3
    }, {
        "delay": 99.6
    }, {
        "delay": 101.5
    }, {
        "delay": 103.4
    }, {
        "delay": 107.2
    }, {
        "delay": 109
    }, {
        "delay": 110.9
    }, {
        "delay": 114.7
    }, {
        "delay": 116.5
    }, {
        "delay": 118.4
    }, {
        "delay": 120.7
    }, {
        "delay": 122.2
    }, {
        "delay": 124
    }, {
        "delay": 125.9
    }]
}
export let song = {
    "name": "KeyBeats",
    "id": "keybeats",
    "src": "assets/audio/music/keybeats.mp3",
    "duration": 146.33795,
    "globalDuration": 3,
    "maxMiss": 3,
    "difficulty": 'hard',
    "colorScheme": 'blue',
    "waveColor": '#f1faff',
    "tracks": [a, s, d, f]
}