export let a = {
    "next": 0,
    "notes": [{
        "delay": 1.3
    }, {
        "delay": 3.1
    }, {
        "delay": 5
    }, {
        "delay": 6.9
    }, {
        "delay": 8.7
    }, {
        "delay": 10.6
    }, {
        "delay": 12.5
    }, {
        "delay": 14.3
    }, {
        "delay": 16.2
    }, {
        "delay": 18
    }, {
        "delay": 20
    }, {
        "delay": 21.8
    }, {
        "delay": 23.7
    }, {
        "delay": 25.6
    }, {
        "delay": 27.4
    }, {
        "delay": 29.3
    }, {
        "delay": 31.1
    }, {
        "delay": 33
    }, {
        "delay": 34.9
    }, {
        "delay": 36.8
    }, {
        "delay": 38.7
    }, {
        "delay": 40.6
    }, {
        "delay": 42.5
    }, {
        "delay": 44.4
    }, {
        "delay": 46.3
    }, {
        "delay": 47.1
    }, {
        "delay": 48
    }, {
        "delay": 48.9
    }, {
        "delay": 49.9
    }, {
        "delay": 50.7
    }, {
        "delay": 51.6
    }, {
        "delay": 52.6
    }, {
        "delay": 54.1
    }, {
        "delay": 55.6
    }, {
        "delay": 57.4
    }, {
        "delay": 59.3
    }, {
        "delay": 61.2
    }, {
        "delay": 62.6
    }, {
        "delay": 64
    }, {
        "delay": 65.3
    }, {
        "delay": 66.8
    }, {
        "delay": 68.2
    }, {
        "delay": 69.6
    }, {
        "delay": 71.9
    }, {
        "delay": 74.3
    }, {
        "delay": 76.2
    }, {
        "delay": 78.4
    }, {
        "delay": 80.6
    }, {
        "delay": 82.7
    }, {
        "delay": 85
    }, {
        "delay": 86.9
    }, {
        "delay": 88.7
    }, {
        "delay": 90.6
    }, {
        "delay": 92.5
    }, {
        "delay": 94.4
    }, {
        "delay": 96.3
    }, {
        "delay": 98.7
    }, {
        "delay": 100.1
    }, {
        "delay": 100.6
    }, {
        "delay": 102.4
    }, {
        "delay": 103.8
    }, {
        "delay": 104.3
    }, {
        "delay": 106.2
    }, {
        "delay": 107.6
    }, {
        "delay": 108.1
    }, {
        "delay": 110
    }, {
        "delay": 111.3
    }, {
        "delay": 111.8
    }, {
        "delay": 113.8
    }, {
        "delay": 115.1
    }, {
        "delay": 115.6
    }, {
        "delay": 117.4
    }, {
        "delay": 118.8
    }, {
        "delay": 119.3
    }, {
        "delay": 121.2
    }, {
        "delay": 122.5
    }, {
        "delay": 123.1
    }, {
        "delay": 124.9
    }, {
        "delay": 126.3
    }, {
        "delay": 126.8
    }, {
        "delay": 128.7
    }, {
        "delay": 130.9
    }, {
        "delay": 133.2
    }, {
        "delay": 135.3
    }, {
        "delay": 137.6
    }, {
        "delay": 139.9
    }, {
        "delay": 142.2
    }, {
        "delay": 143.7
    }]
};

export let s = {
    "next": 0,
    "notes": [{
        "delay": 1.6
    }, {
        "delay": 3.4
    }, {
        "delay": 5.3
    }, {
        "delay": 7.2
    }, {
        "delay": 9.1
    }, {
        "delay": 11
    }, {
        "delay": 12.8
    }, {
        "delay": 15.8
    }, {
        "delay": 16.6
    }, {
        "delay": 18.4
    }, {
        "delay": 20.3
    }, {
        "delay": 22.2
    }, {
        "delay": 24.1
    }, {
        "delay": 25.9
    }, {
        "delay": 27.8
    }, {
        "delay": 31.5
    }, {
        "delay": 33.4
    }, {
        "delay": 35.3
    }, {
        "delay": 37.1
    }, {
        "delay": 39.1
    }, {
        "delay": 40.9
    }, {
        "delay": 42.8
    }, {
        "delay": 45
    }, {
        "delay": 54.6
    }, {
        "delay": 56.5
    }, {
        "delay": 58.4
    }, {
        "delay": 60.3
    }, {
        "delay": 61.9
    }, {
        "delay": 63.1
    }, {
        "delay": 64.5
    }, {
        "delay": 65.9
    }, {
        "delay": 67.5
    }, {
        "delay": 69.4
    }, {
        "delay": 70.1
    }, {
        "delay": 71.5
    }, {
        "delay": 72.4
    }, {
        "delay": 73.9
    }, {
        "delay": 74.6
    }, {
        "delay": 75.9
    }, {
        "delay": 76.6
    }, {
        "delay": 78
    }, {
        "delay": 78.8
    }, {
        "delay": 80.3
    }, {
        "delay": 80.9
    }, {
        "delay": 82.5
    }, {
        "delay": 83.2
    }, {
        "delay": 84.7
    }, {
        "delay": 85.4
    }, {
        "delay": 86.6
    }, {
        "delay": 87.3
    }, {
        "delay": 88.4
    }, {
        "delay": 89.1
    }, {
        "delay": 90.3
    }, {
        "delay": 91
    }, {
        "delay": 92.2
    }, {
        "delay": 92.9
    }, {
        "delay": 94
    }, {
        "delay": 94.8
    }, {
        "delay": 95.9
    }, {
        "delay": 96.6
    }, {
        "delay": 99
    }, {
        "delay": 100.2
    }, {
        "delay": 100.9
    }, {
        "delay": 102.8
    }, {
        "delay": 103.9
    }, {
        "delay": 104.7
    }, {
        "delay": 106.6
    }, {
        "delay": 107.7
    }, {
        "delay": 108.5
    }, {
        "delay": 110.3
    }, {
        "delay": 111.4
    }, {
        "delay": 112.3
    }, {
        "delay": 114.1
    }, {
        "delay": 115.2
    }, {
        "delay": 115.9
    }, {
        "delay": 117.8
    }, {
        "delay": 118.9
    }, {
        "delay": 119.6
    }, {
        "delay": 121.5
    }, {
        "delay": 122.6
    }, {
        "delay": 123.4
    }, {
        "delay": 125.3
    }, {
        "delay": 126.4
    }, {
        "delay": 127.2
    }, {
        "delay": 129.1
    }, {
        "delay": 130.6
    }, {
        "delay": 131.3
    }, {
        "delay": 132.9
    }, {
        "delay": 133.5
    }, {
        "delay": 135
    }, {
        "delay": 135.7
    }, {
        "delay": 137.2
    }, {
        "delay": 138
    }, {
        "delay": 139.5
    }, {
        "delay": 140.3
    }, {
        "delay": 141.8
    }, {
        "delay": 142.5
    }]
};

export let d = {
    "next": 0,
    "notes": [{
        "delay": 1.9
    }, {
        "delay": 3.7
    }, {
        "delay": 4.5
    }, {
        "delay": 5.6
    }, {
        "delay": 7.5
    }, {
        "delay": 8.2
    }, {
        "delay": 9.5
    }, {
        "delay": 11.3
    }, {
        "delay": 12
    }, {
        "delay": 13.2
    }, {
        "delay": 14.8
    }, {
        "delay": 16.9
    }, {
        "delay": 18.8
    }, {
        "delay": 19.5
    }, {
        "delay": 20.7
    }, {
        "delay": 22.5
    }, {
        "delay": 23.2
    }, {
        "delay": 24.4
    }, {
        "delay": 26.3
    }, {
        "delay": 27
    }, {
        "delay": 28.2
    }, {
        "delay": 29.7
    }, {
        "delay": 30.4
    }, {
        "delay": 31.8
    }, {
        "delay": 33.7
    }, {
        "delay": 34.5
    }, {
        "delay": 35.7
    }, {
        "delay": 37.5
    }, {
        "delay": 38.2
    }, {
        "delay": 39.4
    }, {
        "delay": 41.3
    }, {
        "delay": 42
    }, {
        "delay": 43.2
    }, {
        "delay": 45.4
    }, {
        "delay": 53.5
    }, {
        "delay": 56
    }, {
        "delay": 57.9
    }, {
        "delay": 59.7
    }, {
        "delay": 61.6
    }, {
        "delay": 63.4
    }, {
        "delay": 64.9
    }, {
        "delay": 66.3
    }, {
        "delay": 67.8
    }, {
        "delay": 69
    }, {
        "delay": 70.5
    }, {
        "delay": 71.3
    }, {
        "delay": 72.7
    }, {
        "delay": 73.4
    }, {
        "delay": 75
    }, {
        "delay": 75.6
    }, {
        "delay": 76.9
    }, {
        "delay": 77.6
    }, {
        "delay": 79
    }, {
        "delay": 80
    }, {
        "delay": 81.3
    }, {
        "delay": 82.1
    }, {
        "delay": 83.7
    }, {
        "delay": 84.4
    }, {
        "delay": 85.6
    }, {
        "delay": 86.3
    }, {
        "delay": 87.5
    }, {
        "delay": 88.2
    }, {
        "delay": 89.3
    }, {
        "delay": 90
    }, {
        "delay": 91.2
    }, {
        "delay": 92
    }, {
        "delay": 93.1
    }, {
        "delay": 93.8
    }, {
        "delay": 95
    }, {
        "delay": 95.7
    }, {
        "delay": 96.8
    }, {
        "delay": 99.4
    }, {
        "delay": 100.3
    }, {
        "delay": 101.2
    }, {
        "delay": 101.9
    }, {
        "delay": 103.1
    }, {
        "delay": 104
    }, {
        "delay": 105
    }, {
        "delay": 105.7
    }, {
        "delay": 106.9
    }, {
        "delay": 107.8
    }, {
        "delay": 108.8
    }, {
        "delay": 109.5
    }, {
        "delay": 110.6
    }, {
        "delay": 111.5
    }, {
        "delay": 112.5
    }, {
        "delay": 114.4
    }, {
        "delay": 115.3
    }, {
        "delay": 116.3
    }, {
        "delay": 117
    }, {
        "delay": 118.1
    }, {
        "delay": 119
    }, {
        "delay": 120
    }, {
        "delay": 120.8
    }, {
        "delay": 121.8
    }, {
        "delay": 122.7
    }, {
        "delay": 123.8
    }, {
        "delay": 124.4
    }, {
        "delay": 125.6
    }, {
        "delay": 126.5
    }, {
        "delay": 127.5
    }, {
        "delay": 129.5
    }, {
        "delay": 130.1
    }, {
        "delay": 131.5
    }, {
        "delay": 132.6
    }, {
        "delay": 133.8
    }, {
        "delay": 134.7
    }, {
        "delay": 136.2
    }, {
        "delay": 136.9
    }, {
        "delay": 138.4
    }, {
        "delay": 139
    }, {
        "delay": 140.7
    }, {
        "delay": 141.3
    }, {
        "delay": 142.8
    }]
};

export let f = {
    "next": 0,
    "notes": [{
        "delay": 2.1
    }, {
        "delay": 4
    }, {
        "delay": 5.9
    }, {
        "delay": 7.9
    }, {
        "delay": 9.7
    }, {
        "delay": 11.6
    }, {
        "delay": 13.5
    }, {
        "delay": 15.3
    }, {
        "delay": 17.1
    }, {
        "delay": 19.1
    }, {
        "delay": 20.9
    }, {
        "delay": 22.9
    }, {
        "delay": 24.7
    }, {
        "delay": 26.5
    }, {
        "delay": 28.4
    }, {
        "delay": 30.1
    }, {
        "delay": 32.2
    }, {
        "delay": 34.1
    }, {
        "delay": 35.9
    }, {
        "delay": 37.9
    }, {
        "delay": 39.7
    }, {
        "delay": 41.5
    }, {
        "delay": 43.4
    }, {
        "delay": 45.7
    }, {
        "delay": 55
    }, {
        "delay": 57
    }, {
        "delay": 58.9
    }, {
        "delay": 60.8
    }, {
        "delay": 62.2
    }, {
        "delay": 63.8
    }, {
        "delay": 65.7
    }, {
        "delay": 67.1
    }, {
        "delay": 68.7
    }, {
        "delay": 70.9
    }, {
        "delay": 73.2
    }, {
        "delay": 75.3
    }, {
        "delay": 77.2
    }, {
        "delay": 79.5
    }, {
        "delay": 81.8
    }, {
        "delay": 84.1
    }, {
        "delay": 86
    }, {
        "delay": 87.8
    }, {
        "delay": 89.7
    }, {
        "delay": 91.6
    }, {
        "delay": 93.4
    }, {
        "delay": 95.3
    }, {
        "delay": 99.6
    }, {
        "delay": 101.5
    }, {
        "delay": 103.4
    }, {
        "delay": 105.4
    }, {
        "delay": 107.2
    }, {
        "delay": 109.1
    }, {
        "delay": 110.9
    }, {
        "delay": 112.8
    }, {
        "delay": 114.6
    }, {
        "delay": 116.5
    }, {
        "delay": 118.4
    }, {
        "delay": 120.3
    }, {
        "delay": 122.1
    }, {
        "delay": 124
    }, {
        "delay": 125.9
    }, {
        "delay": 127.9
    }, {
        "delay": 129.7
    }, {
        "delay": 131.9
    }, {
        "delay": 134.3
    }, {
        "delay": 136.6
    }, {
        "delay": 138.8
    }, {
        "delay": 140.9
    }, {
        "delay": 143.2
    }]
}
export let song = {
    "name": "KeyBeats",
    "id": "keybeats",
    "src": "assets/audio/music/keybeats.mp3",
    "duration": 146.337959,
    "globalDuration": 4,
    "maxMiss": 5,
    "difficulty": 'normal',
    "colorScheme": 'blue',
    "waveColor": '#f1faff',
    "tracks": [a, s, d, f]
}

